### ISSUE TITLE
invalid function causes crash

### ISSUE THREAD

**Issue by ericglau** [reach-sh/reach-ide#4]
compiler gives error: `error: ./.index.rsh.temp:18:26:application: Invalid function appication. Expected 2 args, got 1 for function defined at reach standard library:33:27:function exp`

index.rsh:
```
'reach 0.1';

const Player =
      { getHand: Fun([], UInt256),
        seeOutcome: Fun([UInt256], Null) };

export const main =
  Reach.App(
    {},
    [['Alice', Player], ['Bob', Player]],
    (A, B) => {
      A.only(() => {
        const handA = declassify(interact.getHand()); });
      A.publish(handA);
      commit();

      B.only(() => {
        const handB = add(interact.getHand());
      });
      B.publish(handB);

      const outcome = (handA + (4 - handB)) % 3;
      commit();

      each([A, B], () => {
        interact.seeOutcome(outcome); });
      exit(); });
```

extension gives error:
```
CallStack (from HasCallStack):
  error, called at src/Reach/AST.hs:58:3 in reach-0.1.2-KZ4oXxVSV3mFfbu8tz29Bg:Reach.AST
  expect_throw, called at src/Reach/Eval.hs:356:10 in reach-0.1.2-KZ4oXxVSV3mFfbu8tz29Bg:Reach.Eval

/Users/eric/git/reach-ide/server/out/server.js:278
        problematicString = problematicString.substring(0, problematicString.length - 1); // remove trailing period at end of sentence 
                                              ^

TypeError: Cannot read property 'substring' of undefined
    at findErrorLocations (/Users/eric/git/reach-ide/server/out/server.js:278:47)
    at /Users/eric/git/reach-ide/server/out/server.js:180:38
    at ChildProcess.exithandler (child_process.js:311:5)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
```

**Comment by ericglau** [comment]
now it doesn't crash but has empty quick fix
